### ISSUE TITLE
two func is missing in the  RGPageViewControllerDelegate

### ISSUE THREAD

**Issue by sing-crystal** [eRGoon/RGPageViewController#11]
cannot find the following 2 optional func on RGPageViewControllerDelegate,and these two func was introduced in the README.md 
![qq20150729-1 2x](https://cloud.githubusercontent.com/assets/7878305/8951741/ebade5ca-3602-11e5-8263-136712a4efbb.png)

optional func colorForTabIndicator() -> UIColor

optional func tintColorForTabBar() -> UIColor?
![qq20150729-2 2x](https://cloud.githubusercontent.com/assets/7878305/8951748/f8d3eca4-3602-11e5-98a6-3d8d72be321a.png)

**Comment by eRGoon** [comment]
sorry. theses protocol methods were removed a while ago.
I forgot to update the README
to change these values you have to override them like this:

``` swift
override var tabIndicatorColor: UIColor {
    get {
        return UIColor.lightGrayColor()
    }
}
override var barTintColor: UIColor? {
    get {
        return nil
    }
}
```

**Comment by sing-crystal** [comment]
Got it. Thanks~
