### ISSUE TITLE
Demo app for sliding UIView?

### ISSUE THREAD

**Issue by datomnurdin** [eRGoon/RGPageViewController#12]
I didn't see any sliding UIView demo app inside your Xcode project.

<img src="https://camo.githubusercontent.com/75e3f206f7b4c6004c7fede36cc5a9b5314a1424/687474703a2f2f6572676f6f6e2e6769746875622e696f2f52475061676556696577436f6e74726f6c6c65722f696d616765732f64656661756c742e706e67">

Please advice. Thank you.

**Comment by eRGoon** [comment]
I updated the Demo project
