### ISSUE TITLE
how to set current index

### ISSUE THREAD

**Issue by syarizat** [eRGoon/RGPageViewController#14]
i want to set current index to tab 2 for the first time launch the app.

**Comment by eRGoon** [comment]
if your viewcontroller is the initial viewcontroller of your app, then you need to set the currentTabIndex by implementing one of the init methods like this:

``` swift
override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

    self.currentTabIndex = 1
}

required init?(coder aDecoder: NSCoder) {
    self.currentTabIndex = 1
}
```

**Comment by syarizat** [comment]
Ok thanks a lot.
