### ISSUE TITLE
Rotating Issue?

### ISSUE THREAD

**Issue by thihaaung6245** [eRGoon/RGPageViewController#21]
First of all,its the first library which can use dynamic tab and dynamic content for each tab without need to initiate view controllers manually like other library do.You just use one controller and change data according to each index.Yeah pretty smart one.Thanks for your hard work...

But,I really do have some problem.If you have some time,can you fix it?
<img width="668" alt="screenshot 2016-04-14 02 34 00" src="https://cloud.githubusercontent.com/assets/10526402/14507751/37912cbe-01ea-11e6-8efd-44603dfe636a.png">

When rotating the device,it appear like that..

**Comment by eRGoon** [comment]
I'll check it

**Comment by htarwara6245** [comment]
I will be waiting for your reply...Thanks for the check.

**Comment by htarwara6245** [comment]
Ummm any help???please?do you still working on?;(
