### ISSUE TITLE
Navbar bottom border line

### ISSUE THREAD

**Issue by sakae-nakajima** [eRGoon/RGPageViewController#3]
I have RGPageViewController in NavigationController. It is working as expected. However, the bottom border line is missing from Navigation Bar when user opens a view controller from the RGPageViewController. I am not sure if this is related with RGPageViewController.

**Comment by eRGoon** [comment]
it is indeed somehow intended if the tabbar is attached to the the top. otherwise this borderline is visible between the navigation bar and the tabbar.

i'll try to provide a fix for that soon
