### ISSUE TITLE
how to reload data?

### ISSUE THREAD

**Issue by taylor19882002** [eRGoon/RGPageViewController#4]
hi, thx for this implementation and as title, how to reload data ?

**Comment by TangSirOnGit** [comment]
hi, how about this issue now?
thanks.

**Comment by taylor19882002** [comment]
A dirty solution 

in MyViewController: RGPageViewController,RGPageViewControllerDataSource,RGPageViewControllerDelegate, ...

``` swift
self.needsSetup=true
self.setupSelf()
self.currentTabIndex=0
self.selectTabAtIndex(self.currentTabIndex)
```

**Comment by eRGoon** [comment]
there is a reloadData Function
