### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by velthune** [eRGoon/RGPageViewController#7]
As suggested in "Install" section of Readme, I just copy RGPageViewController.swift file in my project.

Unfortunately there are a lot of compile errors, first at line 142:

```
        self.view.addConstraints(constraints)
```

"Cannot invoke 'addContraints' with an argument list of type '(NSMutableArray!)'"

Other errors are all where you use "as" with the error:

" 'Any object' is not convertible to .... :did you mean to use 'as!' to force downcast?"

**Comment by DanielSmith1239** [comment]
replace "as" with "as!", and replace the layoutSubviews function with:

```
    private func layoutSubviews() {
         var constraints: NSMutableArray!

         switch self.tabbarPosition {
         case .Top:
             constraints = layoutTabbarTop()
         case .Bottom:
             constraints = layoutTabbarBottom()
         case .Left:
             constraints = layoutTabbarLeft()
         case .Right:
             constraints = layoutTabbarRight()
         }

         var constraintsNew: Array = constraints as [AnyObject]

         self.view.addConstraints(constraintsNew)

         self.needsLayoutSubviews = false
    }
```
